### ISSUE TITLE
unable to do cloudberry backup because of "pathing" error?

### ISSUE THREAD

**Issue by BilliumG** [minio/awesome-minio#22]
Could very well be user but here is the information.  Any assistance will be helpful.

error code:
time="2016-11-25T21:41:05-06:00" level=error msg="Unable to create an object." cause="mkdir \\\\?\\c:\\backups\\backups\\testing\\MBS-eb2917ef-a3bc-4e8e-8652-3a1cb2fdb7e8\\CBB_HUNTING_WABBIT\\C:: The filename, directory name, or volume label syntax is incorrect." source="[object-handlers.go:447:objectAPIHandlers.PutObjectHandler()]" stack="/home/harsha/mygo/src/github.com/minio/minio/cmd/fs-v1.go:465:fsObjects.PutObject <autogenerated>:195:(*fsObjects).PutObject /home/harsha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:433:objectAPIHandlers.PutObjectHandler /home/harsha/mygo/src/github.com/minio/minio/cmd/api-router.go:58:(objectAPIHandlers).PutObjectHandler-fm"

**Comment by koolhead17** [comment]
Hello @BilliumG Is your bucket name correct because the error ``The filename, directory name, or volume label syntax is incorrect."`` ? 
Also please follow [https://github.com/minio/cookbook/blob/master/docs/how-to-use-cloudberry-drive-with-minio.md](https://github.com/minio/cookbook/blob/master/docs/how-to-use-cloudberry-drive-with-minio.md)

Also adding @erudinsky to the thread. 😄

**Comment by erudinsky** [comment]
@BilliumG where do you run Minio? Windows? What backup type (file level etc) / what settings applied?

**Comment by harshavardhana** [comment]
Moving this to minio server.
